### PR TITLE
Update component name

### PR DESCRIPTION
**Pull request by a-magdy**
Update the generated component and container names in newly created folder to include the path of the component (includes whatever after the imports/components)

If you choose a component name "bla" under the path: `src/imports/client/components/members/requests`

the generated display names for the container & component respectively will be:

`MembersRequestsBlaContainer`
`MembersRequestsBlaComponent`

---
This change is [Reviewable](https://reviewable.io/reviews/quadric/qelectron/6)

### CODE REVIEW

**Comment by a-magdy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by zvictor** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[generators/app/index.js, line 72 at r1](https://reviewable.io:443/reviews/quadric/qelectron/6#-KvaUwdO9lhqAPwxVQCh:-KvaUwdO9lhqAPwxVQCi:b-6x88eu) ([raw file](https://github.com/quadric/qelectron/blob/3097364c15a0f84a66c1ab998eef1da41c619282/generators/app/index.js#L72)):*
>  props.componentKey = (this.currentFolderName === props.name) ? props.name : `${getComponentKey(this.destinationRoot())}/${props.name}` || props.name;

reviewing the code I realised that there are no conceptual differences between `props.fullCamelName` and `props.componentKey`. Both try to achieve the same goal. Therefore I would suggest fixing `props.componentKey` instead of duplicating logic.

It seems that a possible solution to this issue could simply be:

```js
props.componentKey =`${getComponentKey(this.destinationRoot())}/${props.name}`
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by zvictor** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generators/app/index.js, line 72 at r1](https://reviewable.io:443/reviews/quadric/qelectron/6#-KvaUwdO9lhqAPwxVQCh:-KvaWan2VuyKryNKu1wK:bx0ru3) ([raw file](https://github.com/quadric/qelectron/blob/3097364c15a0f84a66c1ab998eef1da41c619282/generators/app/index.js#L72)):*
<details><summary><i>Previously, zvictor (zVictor) wrote…</i></summary><blockquote>

>  props.componentKey = (this.currentFolderName === props.name) ? props.name : `${getComponentKey(this.destinationRoot())}/${props.name}` || props.name;

reviewing the code I realised that there are no conceptual differences between `props.fullCamelName` and `props.componentKey`. Both try to achieve the same goal. Therefore I would suggest fixing `props.componentKey` instead of duplicating logic.

It seems that a possible solution to this issue could simply be:

```js
props.componentKey =`${getComponentKey(this.destinationRoot())}/${props.name}`
```
</blockquote></details>

forgot it! we need to improve `camelName`, not `componentKey`. My mistake. Would it then be a good idea to make `camelName` based on `componentKey`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by a-magdy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generators/app/index.js, line 72 at r1](https://reviewable.io:443/reviews/quadric/qelectron/6#-KvaUwdO9lhqAPwxVQCh:-KvbvkV0SN9a3Dj4MUHV:b-bqwj3e) ([raw file](https://github.com/quadric/qelectron/blob/3097364c15a0f84a66c1ab998eef1da41c619282/generators/app/index.js#L72)):*
<details><summary><i>Previously, zvictor (zVictor) wrote…</i></summary><blockquote>

forgot it! we need to improve `camelName`, not `componentKey`. My mistake. Would it then be a good idea to make `camelName` based on `componentKey`?
</blockquote></details>

What do you mean by this? .. should I combine camelName & fullCamelName .. and just have camelName as the fullCamelName?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by zvictor** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generators/app/index.js, line 72 at r1](https://reviewable.io:443/reviews/quadric/qelectron/6#-KvaUwdO9lhqAPwxVQCh:-KwZpsTQxaU5XnXX2Ayr:b-byq8lb) ([raw file](https://github.com/quadric/qelectron/blob/3097364c15a0f84a66c1ab998eef1da41c619282/generators/app/index.js#L72)):*
<details><summary><i>Previously, a-magdy (Ahmad Magdy) wrote…</i></summary><blockquote>

What do you mean by this? .. should I combine camelName & fullCamelName .. and just have camelName as the fullCamelName?
</blockquote></details>

forgot what I said and let's just cleanup the names. we don't need all 3: `baseCamelName`, `camelName` and  `fullCamelName`.
try to reduce it to the minimum needed. less code, less maintenance. =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by a-magdy** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[generators/app/index.js, line 72 at r1](https://reviewable.io:443/reviews/quadric/qelectron/6#-KvaUwdO9lhqAPwxVQCh:-KwZvPVGTGjwtTzv14Bk:b-896fix) ([raw file](https://github.com/quadric/qelectron/blob/3097364c15a0f84a66c1ab998eef1da41c619282/generators/app/index.js#L72)):*
<details><summary><i>Previously, zvictor (zVictor) wrote…</i></summary><blockquote>

forgot what I said and let's just cleanup the names. we don't need all 3: `baseCamelName`, `camelName` and  `fullCamelName`.
try to reduce it to the minimum needed. less code, less maintenance. =)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Comment by zvictor** [comment]
Reviewed 1 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/quadric/qelectron/6)*

**Pull request merged**
